// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ernesto.Sanchez.OrderService.Domain.Orders.Entities;

public partial class Order
{
    public Guid OrderId { get; set; }

    public string Client { get; set; }

    public DateTimeOffset? DateofOrder { get; set; }

    public string AdressClient { get; set; }

    public string District { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}